const profilesJSON = [{
            "firstName": "Jonas",
            "lastName": "Karlsen",
            "age": "32",
            "imageSrc": "",
            "description": "",
            "gender": "Male"
        }, {
            "firstName": "Mari",
            "lastName": "Olsen",
            "age": "29",
            "imageSrc": "",
            "description": "",
            "gender": "Female"
        }, {
            "firstName": "Birgitte",
            "lastName": "Jensen",
            "age": "32",
            "imageSrc": "",
            "description": "",
            "gender": "Female"
        }, {
            "firstName": "Kari",
            "lastName": "Johansen",
            "age": "26",
            "imageSrc": "",
            "description": "",
            "gender": "Female"
        }, {
            "firstName": "Lars",
            "lastName": "Johansson",
            "age": "33",
            "imageSrc": "",
            "description": "",
            "gender": "Male"
        }, {
            "firstName": "Tore",
            "lastName": "Halvorsen",
            "age": "29",
            "imageSrc": "",
            "description": "",
            "gender": "Male"
        }, {
            "firstName": "Jenny",
            "lastName": "Jensen",
            "age": "34",
            "imageSrc": "",
            "description": "",
            "gender": "Female"
        }, {
            "firstName": "Karl",
            "lastName": "Ivarsen",
            "age": "27",
            "imageSrc": "",
            "description": "",
            "gender": "Male"
        }];